Update torch and numpy dependencies
Attempting to install requirements.txt using Python 3.11 resulted in
this error:

    ERROR: Could not find a version that satisfies the requirement torch
	==1.11.0 (from versions: 2.0.0, 2.0.1)

Torch has a major version bump, but it is still backwards-compatible,
and to boot now has a compile feature which is supposed to speed things
up.